#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'lotus/setup'
require 'json'
require_relative '../lib/cricos_api'

if ARGV.count == 0
  puts "Usage: import_institutions [instiutions.json]"
else
  ARGF.each_line do |e|
    line = JSON.parse(e)

    institution = InstitutionRepository.find_or_initialize_by_provider_code(line['provider_code'])

    institution.provider_id = line['provider_id']
    institution.trading_name = line['trading_name']
    institution.name = line['name']
    institution.type = line['type']
    institution.postal_address = line['postal_address']
    institution.website = line['website']
    institution.total_capacity = line['total_capacity']

    institution = InstitutionRepository.persist(institution)

    unless institution.id.nil?
      institution.locations = line['locations'].map do |lc|
        location_id = lc['location_id']
        location = LocationRepository.find_or_initialize_by_institution_id_and_location_id(institution.id, location_id)
        location.name = lc['name']
        location.state = lc['state']
        location.number_of_courses = lc['number_of_courses']
        LocationRepository.persist(location)
      end

      institution.contact_officers = line['contact_officers'].map do |co|
        contact_officer = ContactOfficerRepository.find_or_initialize_by_institution_id_and_name(institution.id, co['name'])
        contact_officer.role = co['role']
        contact_officer.title = co['title']
        contact_officer.phone = co['phone']
        contact_officer.fax = co['fax']
        contact_officer.email = co['email']
        ContactOfficerRepository.persist(contact_officer)
      end
    end

    puts institution.inspect

  end
end
