#!/bin/sh

echo "Bootstrap app"

echo "Bundling .."

bundle install -j4

echo "Prepare DB .."

bundle exec lotus db prepare

echo "If you want to import data,"
echo "please place dumped institutions.json into db/data"
echo "then run"
echo "./script/import_institutions db/data/institutions.json"

echo "DONE"
